#!/bin/bash
DIRNAME=output
SIZE_MB=8
NUM_FILES=10000

. ./progbar

progbar_init

mkdir -p $DIRNAME
pushd $DIRNAME > /dev/null
for i in $(seq 1 $NUM_FILES); do
    zi=$(printf "%06d" $i)
    fn="file$zi.dat"
    cn="$fn.md5"
    dd if=/dev/urandom of=$fn bs=1M count=$SIZE_MB > /dev/null 2>&1
    md5sum $fn > $cn
    progbar_show $i $NUM_FILES
done

progbar_init

popd > /dev/null
