#!/bin/bash

_last_progress=-1

# 0. Initialize
function progbar_init {
    printf "\n"
    _last_progress=-1
}

# 1. Create ProgressBar function
# 1.1 Input is currentState($1) and totalState($2)
function progbar_show {
    # Process data
    let _progress=(${1}*100/${2}*100)/100

    if [ $_progress -eq $_last_progress ]; then
        return
    fi
    _last_progress=$_progress

    let _done=(${_progress}*4)/10
    let _left=40-$_done

    # Build progressbar string lengths
    _fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")

    # 1.2 Build progressbar strings and print the ProgressBar line
    # 1.2.1 Output example:
    # 1.2.1.1 Progress : [########################################] 100%
    printf "\rProgress : [${_fill// /#}${_empty// /-}] ${_progress}%%"
}


